<?php
//エラー表示あり
ini_set('display_errors',1);
//日本時間にする
date_default_timezone_set('Asia/Tokyo');
//URL/デレクトリ設定
define('HOME_URL','/TwitterClone/Views/');
//データベースの接続情報
define('DB_HOST','localhost');
define('DB_USER','Root');
define('DB_PASSWORD','FdWv9vADDI.o');
define('DB_NAME','twitter_clone');
?>